In [20]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas_datareader import data
from sklearn.preprocessing import MinMaxScaler
import pandas.tseries.offsets as offsets

In [21]:
# 一次元目のリストの要素の数を８個にする
a = np.array([0, 10, 20, 30, 40, 50, 60, 70])
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [22]:
a.shape

(8,)

In [23]:

b = a.reshape(-1, 4)
b

array([[ 0, 10, 20, 30],
       [40, 50, 60, 70]])

In [24]:
b.shape

(2, 4)

In [25]:
c = a.reshape(-1, 4, 2)
c

array([[[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70]]])

In [26]:
c.shape

(1, 4, 2)

In [27]:
d = np.array([0.0, 11.1, 22.2, 33.3, 44.4, 55.5, 66.6, 77.7])
d

array([ 0. , 11.1, 22.2, 33.3, 44.4, 55.5, 66.6, 77.7])

In [28]:
e = torch.IntTensor(d)
e

tensor([ 0, 11, 22, 33, 44, 55, 66, 77], dtype=torch.int32)

In [29]:
f = torch.FloatTensor(d)
f

tensor([ 0.0000, 11.1000, 22.2000, 33.3000, 44.4000, 55.5000, 66.6000, 77.7000])

In [30]:
g = f.view(4, -1)
g

tensor([[ 0.0000, 11.1000],
        [22.2000, 33.3000],
        [44.4000, 55.5000],
        [66.6000, 77.7000]])

In [31]:
g.shape

torch.Size([4, 2])

In [32]:
a = a.reshape(-1, 1)
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70]])

In [33]:
# 最大値と最小値を設定したインスタンスを作成し、変数「scaler」に代入
scaler = MinMaxScaler(feature_range=(-1, 1))

# 最大値と最小値を計算
scaler.fit(a)

# 設定した大きさに数値を変換
a = scaler.transform(a)

# 二次元のNumpy Array
a

array([[-1.        ],
       [-0.71428571],
       [-0.42857143],
       [-0.14285714],
       [ 0.14285714],
       [ 0.42857143],
       [ 0.71428571],
       [ 1.        ]])

In [34]:
a = torch.FloatTensor(a)

# 二次元のPytorch Tensor
a

tensor([[-1.0000],
        [-0.7143],
        [-0.4286],
        [-0.1429],
        [ 0.1429],
        [ 0.4286],
        [ 0.7143],
        [ 1.0000]])

In [35]:
b = a.view(-1)
b

tensor([-1.0000, -0.7143, -0.4286, -0.1429,  0.1429,  0.4286,  0.7143,  1.0000])